### Variables
@apiUrl = http://localhost:3000

### GET Hello World
GET {{apiUrl}} 

### POST New Restaurant
POST {{apiUrl}}/restaurant/create
Content-Type: application/json

{
    "name": "Mais Pizza",
    "description": "An exquisite pigeon roast, infused with the essence of custard apple, slow-roasted to bring out its natural flavors and served with a side of creamy parsnip",
    "phone": "(86) 31779-2768",
    "ownerId": "019f378c-6008-7376-addb-e1f2d779fe90",
    "street": "Fabrício Alameda",
    "city": "Xavier de Nossa Senhora",
    "complement": "",
    "neighborhood": "Setor 3",
    "state": "Santa Catarina",
    "streetNumber": "537",
    "zipCode": "70583-185",
    "document": "9697679030678"
}

### GET List Restaurant By Owner
GET {{apiUrl}}/restaurant/owner/019f378c-6

### POST Create New Item to Menu
POST {{apiUrl}}/menu/019f392d-55ca-711a-a414-19517b1923ec
Content-Type: application/json

{
    "name": "Goose With Dragonfruit Sauce",
    "description": "A classic pie filled with delicious goose and crunchy beans, baked in a tender pastry crust and topped with a golden-brown lattice.",
    "priceInCents": 11239,
    "isVegetarian": false,
    "isAvailable": false
}

### GET List Items to Menu
GET {{apiUrl}}/menu/019f392d-55ca-711a-a412-19517b1923ec

### GET Get Item to Menu
GET {{apiUrl}}/menu/019f392d-55ca-711a-a412-19517b1923ec/019f47e7-10d7-70e7-9b1a-ebb622012b60


### POST Create New Item