@apiUrl = http://localhost:3000

### GET Hello World
GET {{apiUrl}} 


### CATEGORIES

### POST Create New Restaurant Category
POST {{apiUrl}}/categories/restaurant
Content-Type: application/json

{
    "name": "Lanchonete"
}

### GET List Restaurant Categories (Paginated)
GET {{apiUrl}}/categories/restaurant?page=1&limit=10

### GET Restaurant Category by ID
GET {{apiUrl}}/categories/restaurant/019f4c51-5404-7209-b1ad-b96cb1df7756

### PUT Update Restaurant Category
PUT {{apiUrl}}/categories/restaurant/019f4c51-5404-7209-b1ad-b96cb1df7756
Content-Type: application/json

{
    "name": "Pizzarias"
}

### DELETE Restaurant Category
DELETE {{apiUrl}}/categories/restaurant/019f4c51-5404-7209-b1ad-b96cb1df7756

### POST Create New Product Category
POST {{apiUrl}}/categories/product
Content-Type: application/json

{
    "name": "maIS pedIdOS eSSe ano"
}

### GET List Product Categories (Paginated)
GET {{apiUrl}}/categories/product?page=1&limit=10

### GET Product Category by ID
GET {{apiUrl}}/categories/product/019f4c61-1ee0-71f9-81f7-af477ac48792

### PUT Update Product Category
PUT {{apiUrl}}/categories/product/019f4c61-1ee0-71f9-81f7-af477ac48792
Content-Type: application/json

{
    "name": "Novos Pedidos do Ano"
}

### DELETE Product Category
DELETE {{apiUrl}}/categories/product/019f4c61-1ee0-71f9-81f7-af477ac48792


### RESTAURANT

### POST New Restaurant
POST {{apiUrl}}/restaurant
Content-Type: application/json

{
    "name": "Mais Pizza",
    "description": "An exquisite pigeon roast, infused with the essence of custard apple, slow-roasted to bring out its natural flavors and served with a side of creamy parsnip",
    "phone": "(86) 31779-2768",
    "ownerId": "019f378c-6008-7376-addb-e1f2d779fe90",
    "street": "Fabrício Alameda",
    "city": "Xavier de Nossa Senhora",
    "categoryId": "019f4c51-5404-7209-b1ad-b96cb1df7756",
    "complement": "",
    "neighborhood": "Setor 3",
    "state": "Santa Catarina",
    "streetNumber": "537",
    "zipCode": "70583-185",
    "document": "9697679030678"
}

### GET List Restaurant By Owner
GET {{apiUrl}}/restaurant/owner/019f378c-6008-7376-addb-e1f2d779fe90


### MENU (PRODUCTS)

### POST Create New Item to Menu
POST {{apiUrl}}/menu/019f4c9e-936e-76c8-a367-b6f3033a6ba1
Content-Type: application/json

{
    "name": "broccolini",
    "description": "A robust crunchy stew featuring Cantonese flavors, loaded with zesty meat, crispy vegetables, and a sweet, sour broth.",
    "priceInCents": 87,
    "categoryId": "019f4c61-1ee0-71f9-81f7-af477ac48792",
    "isVegetarian": false,
    "isAvailable": false
}

### GET List Items to Menu
GET {{apiUrl}}/menu/019f392d-55ca-711a-a412-19517b1923ec

### GET Get Item to Menu
GET {{apiUrl}}/menu/019f392d-55ca-711a-a412-19517b1923ec/019f47e7-10d7-70e7-9b1a-ebb622012b60

### DELETE Item to Menu
DELETE {{apiUrl}}/menu/019f4c9e-936e-76c8-a367-b6f3033a6ba1/019f4c9f-4e45-702c-bda0-6d4ed53a3b13
