services:
  db:
    image: bitnami/postgresql:latest
    container_name: rangoo_db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=rangoo_user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=rangoo_db
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
